# Preview portfolio output files

Display the first five rows of the final portfolio CSV and Parquet outputs.

In [1]:
from pathlib import Path

import pandas as pd
from IPython.display import display

root = Path.cwd()
if not (root / "handoff" / "final").is_dir():
    root = root.parent

csv_path = root / "handoff" / "final" / "portfolio_dashboard.csv"
parquet_path = root / "handoff" / "final" / "portfolio_dashboard.parquet"

print("CSV output — first 5 rows")
display(pd.read_csv(csv_path, dtype={"merchant_abn": "string"}, nrows=5))

print("Parquet output — first 5 rows")
display(pd.read_parquet(parquet_path).head(5))

print("Finished.")

CSV output — first 5 rows

,portfolio_id,as_of,currency,retention,merchant_abn,merchant_name,merchant_category,merchant_expected_monthly_gross_fees,rank_by_expected_fees,portfolio_expected_monthly_gross_fees,...,portfolio_expected_fee_retention,portfolio_size,variability_weight,concentration_weight,window_start,window_end,portfolio_score_lower_bound,portfolio_optimality_gap,portfolio_certified,portfolio_status
0,2022-09-30_26w_n100_w0.5_r1.0,2022-09-30,AUD,1.0,79827781481,Amet Risus Inc.,"furniture, home furnishings and equipment shop...",33161.999483,1,1.666400e+06,...,1.0,100,0.5,0.5,2022-03-28,2022-09-25,100.0,0.0,True,unique_maximum_revenue_portfolio
1,2022-09-30_26w_n100_w0.5_r1.0,2022-09-30,AUD,1.0,48534649627,Dignissim Maecenas Foundation,"opticians, optical goods, and eyeglasses",31088.087839,2,1.666400e+06,...,1.0,100,0.5,0.5,2022-03-28,2022-09-25,100.0,0.0,True,unique_maximum_revenue_portfolio
2,2022-09-30_26w_n100_w0.5_r1.0,2022-09-30,AUD,1.0,32361057556,Orci In Consequat Corporation,"gift, card, novelty, and souvenir shops",31053.347465,3,1.666400e+06,...,1.0,100,0.5,0.5,2022-03-28,2022-09-25,100.0,0.0,True,unique_maximum_revenue_portfolio
3,2022-09-30_26w_n100_w0.5_r1.0,2022-09-30,AUD,1.0,86578477987,Leo In Consulting,"watch, clock, and jewelry repair shops",30586.118562,4,1.666400e+06,...,1.0,100,0.5,0.5,2022-03-28,2022-09-25,100.0,0.0,True,unique_maximum_revenue_portfolio
4,2022-09-30_26w_n100_w0.5_r1.0,2022-09-30,AUD,1.0,38700038932,Etiam Bibendum Industries,tent and awning shops,30106.623490,5,1.666400e+06,...,1.0,100,0.5,0.5,2022-03-28,2022-09-25,100.0,0.0,True,unique_maximum_revenue_portfolio

Parquet output — first 5 rows

,portfolio_id,as_of,currency,retention,merchant_abn,merchant_name,merchant_category,merchant_expected_monthly_gross_fees,rank_by_expected_fees,portfolio_expected_monthly_gross_fees,...,portfolio_expected_fee_retention,portfolio_size,variability_weight,concentration_weight,window_start,window_end,portfolio_score_lower_bound,portfolio_optimality_gap,portfolio_certified,portfolio_status
0,2022-09-30_26w_n100_w0.5_r1.0,2022-09-30,AUD,1.0,79827781481,Amet Risus Inc.,"furniture, home furnishings and equipment shop...",33161.999483,1,1.666400e+06,...,1.0,100,0.5,0.5,2022-03-28,2022-09-25,100.0,0.0,True,unique_maximum_revenue_portfolio
1,2022-09-30_26w_n100_w0.5_r1.0,2022-09-30,AUD,1.0,48534649627,Dignissim Maecenas Foundation,"opticians, optical goods, and eyeglasses",31088.087839,2,1.666400e+06,...,1.0,100,0.5,0.5,2022-03-28,2022-09-25,100.0,0.0,True,unique_maximum_revenue_portfolio
2,2022-09-30_26w_n100_w0.5_r1.0,2022-09-30,AUD,1.0,32361057556,Orci In Consequat Corporation,"gift, card, novelty, and souvenir shops",31053.347465,3,1.666400e+06,...,1.0,100,0.5,0.5,2022-03-28,2022-09-25,100.0,0.0,True,unique_maximum_revenue_portfolio
3,2022-09-30_26w_n100_w0.5_r1.0,2022-09-30,AUD,1.0,86578477987,Leo In Consulting,"watch, clock, and jewelry repair shops",30586.118562,4,1.666400e+06,...,1.0,100,0.5,0.5,2022-03-28,2022-09-25,100.0,0.0,True,unique_maximum_revenue_portfolio
4,2022-09-30_26w_n100_w0.5_r1.0,2022-09-30,AUD,1.0,38700038932,Etiam Bibendum Industries,tent and awning shops,30106.623490,5,1.666400e+06,...,1.0,100,0.5,0.5,2022-03-28,2022-09-25,100.0,0.0,True,unique_maximum_revenue_portfolio

Finished.